cawbutler:
  userName: tom
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.me:8010/eureka
spring:
  application:
    name: config-client
server:
  port: 9101